### ISSUE TITLE
Add Visibility Constraint Contexts

### ISSUE THREAD

**Issue by yannduran** [madskristensen/VsctIntellisense#2]
Adding **visibility contexts** would be very handy.

Example:

```
  <VisibilityConstraints>
    <VisibilityItem guid="PackageCommandSet" id="InsertGuidCommand"
      context="UICONTEXT_CodeWindow"/> ~
  </VisibilityConstraints>
```
Disclaimer:
  ~ I'm not sure thing is correct syntax yet, hence this request

Questions:

1. Is `VisibilityItem` the same thing as `VisibilityConstraint`, or does the latter not exist?
2. If this can't be added as requested, **where** do we find a list of contexts that are valid for `VSCT` files?

**Comment by madskristensen** [comment]
This was added long ago, but I forgot to close out this issue.

1. The latter doesn't exist
2. It was added :)
